### ISSUE TITLE
Animation frame task

### ISSUE THREAD

**Issue by plehegar** [w3c/animation-timing#1]
From
 http://lists.w3.org/Archives/Public/public-web-perf/2014Jul/0115.html

The concept defined by "Timing control for script-based animations"
http://w3c.github.io/animation-timing/
seems to be more widely applicable and needs to be made extensible.

In particular user agents are interested in processing scroll events,
media query evaluation, fullscreen state changes, orientation changes,
and probably much more layout related matters in the same task.

See https://www.w3.org/Bugs/Public/show_bug.cgi?id=26440 for some context.

This argues that this animation frame task needs some internal
queuing. Either we need buckets so scroll events are always processed
before any fullscreen state changes, or we need a simple FIFO queuing
mechanism on a per-task basis.

Who will take ownership of this?

**Comment by annevk** [comment]
This is done now, right? This whole specification has been merged into HTML's event loop model so it should probably just be published as a note with a forward pointer.

**Comment by plehegar** [comment]
probably indeed

**Comment by annevk** [comment]
Why did you close this without making it a note?

**Comment by plehegar** [comment]
Because the Group never resolved to make the note, so we're in the limbo situation which is far from ideal.

**Comment by annevk** [comment]
You also did not resolve otherwise, so why did you close this?

**Comment by plehegar** [comment]
I'll bring it up again in September and see if we can get closure on it.

**Comment by annevk** [comment]
Reopen this meanwhile?

**Comment by toddreifsteck** [comment]
Re-opened for tracking until we've 100% closed on this.

**Comment by plehegar** [comment]
We'll publish a Note on September 22 to redirect.
