### ISSUE TITLE
requestAnimationFrame is no longer part of HTML 5.1

### ISSUE THREAD

**Issue by takenspc** [w3c/animation-timing#5]
The links of README.md and index.html

> See http://www.w3.org/TR/html51/webappapis.html#animation-frames

are broken because requestAnimationFrame is no longer part of HTML 5.1.

I think the files should reference [HTML Living Standard](https://html.spec.whatwg.org/multipage/webappapis.html#animation-frames) like [Web Storage](https://w3c.github.io/webstorage/) and [Web Workers](https://w3c.github.io/workers/)

**Comment by siusin** [comment]
See <a href="https://github.com/w3c/html/issues/159">html/issues/159</a>.

Not sure why this API was removed from the HTML 5.1 spec...

**Comment by siusin** [comment]
Please follow up [the plan in W3C/HTML](https://github.com/w3c/html/issues/159#issuecomment-208644858).
